---
driver:
  name: docker
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles

platforms:

  - name: noobuntu_update_rocky8
    image: rockylinux:8
    privileged: true
    override_command: false

  - name: noobuntu_update_rocky9
    image: rockylinux:9
    privileged: true
    override_command: false

  - name: noobuntu_update_ubuntu1804
    image: ubuntu:18.04
    privileged: true
    override_command: false

  - name: noobuntu_update_ubuntu2004
    image: ubuntu:20.04
    privileged: true
    override_command: false

  - name: noobuntu_update_ubuntu2204
    image: ubuntu:22.04
    privileged: true
    override_command: false
