---
- name: File context inventory
  shell: "semanage fcontext --list -C | grep -F '{{ item.pattern }}'"
  failed_when: false
  changed_when: false
  register: item_record

- name: Add file context record
  shell: semanage fcontext --add -t "{{ item.type }}" "{{ item.pattern }}"
  when: item_record.rc != 0
  register: record_add

# example entry:
# /opt/redmine-.*/log(/.*)?  all files  system_u:object_r:var_log_t:s0
- name: Modify file context record
  shell: semanage fcontext --modify -t "{{ item.type }}" "{{ item.pattern }}"
  when: (item_record.rc == 0) and (item_record.stdout.split(":")[2] != item.type)
  register: record_modify

- name: Apply file context settings
  shell: "restorecon -rv {{ item.path }}"
  register: restorecon_cmd
  changed_when: restorecon_cmd.stdout|length
