---
- name: Check if machine is AD joined
  shell:
    cmd: "realm list | grep 'configured: kerberos-member'"
  failed_when: false
  changed_when: false
  register: ad_status

- fail:
    msg: "Host is not joined to AD. Make sure you run ad.yml, then join to the domain with 'realm join'."
  when: ad_status.rc != 0
