---
- name: Check if Apport is installed
  shell:
    cmd: apt list --installed | grep ^apport/
  failed_when: false
  changed_when: false
  register: apport_pkg

- name: Disable Apport
  ini_file:
    path: /etc/default/apport
    section: null
    option: enabled
    value: '0'
    no_extra_spaces: true
  when: apport_pkg.rc == 0

- name: Disable Apport service
  systemd:
    name: apport
    enabled: false
    state: stopped
  when: apport_pkg.rc == 0

- include_role:
    name: bviktor.sysctl
  loop:
    - { file: '99-corepattern', option: 'kernel.core_pattern', value: "{{ item }}" }
