---
- name: Restart time sync service
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: Force time sync
  command: "timedatectl --adjust-system-clock"

- name: Restart resolved service
  systemd:
    name: systemd-resolved
    state: restarted
  when: (ansible_distribution == 'Ubuntu') or ((ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '8'))

- name: Restart SSSD service
  systemd:
    name: sssd
    state: restarted

- name: Restart Chrony
  systemd:
    name: chronyd
    state: restarted
