---
- name: Install SELinux fundamentals
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - checkpolicy
      - policycoreutils
      - policycoreutils-python-utils
      - python3-libselinux
      - selinux-policy
      - selinux-policy-targeted
  register: installed_selinux
