- name: Install SELinux fundamentals
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - policycoreutils
    - "policycoreutils-python{% if ansible_distribution_major_version != 7 %}-utils{% endif %}"
  register: installed_selinux
