# Perf isn't supported in WSL yet
# https://github.com/microsoft/WSL/issues/8480
- name: Install perf
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - linux-tools-common
    - "linux-tools-{{ ansible_kernel }}"
    - "linux-generic-hwe-{{ ansible_distribution_version }}-edge"
  when: ('microsoft-standard-WSL' not in ansible_kernel)

# https://www.jetbrains.com/help/clion/cpu-profiler.html
- include_role:
    name: sysctl
  loop:
  - { file: '99-perf', option: 'kernel.perf_event_paranoid', value: '1' }
  - { file: '99-perf', option: 'kernel.kptr_restrict', value: '0' }
