#!/bin/bash

# sudo apt -y install git autopoint gtk-doc-tools gobject-introspection libglib2.0-dev

set -eu

PKG_NAME='libsecret'

PKG_VER="0.20.3"
PKG_BUILD=1

SRC_DIR="${PWD}"
TMP_DIR="/tmp/noobuntu"
WORK_DIR="${TMP_DIR}/${PKG_NAME}"
DEST_DIR="${TMP_DIR}/${PKG_NAME}_${PKG_VER}-${PKG_BUILD}"

sudo rm -rf ${TMP_DIR}

mkdir -p ${WORK_DIR}
mkdir -p ${DEST_DIR}

pushd ${WORK_DIR}

git clone https://gitlab.gnome.org/GNOME/libsecret.git
cd libsecret
git checkout ${PKG_VER}

# for whatever reason autogen.sh always fails the first time
./autogen.sh || true
./autogen.sh
./configure --prefix=/usr
make
DESTDIR=${DEST_DIR} make install

mkdir -p "${DEST_DIR}/DEBIAN"

cat << EOF > "${DEST_DIR}/DEBIAN/control"
Package: ${PKG_NAME}
Version: ${PKG_VER}-${PKG_BUILD}
Section: base
Priority: optional
Architecture: amd64
Depends: libglib2.0-0 (>= 2.56.4), libgcrypt20 (>= 1.8.1)
Maintainer: Viktor Berke <github.bviktor@outlook.com>
Description: Library for storing and retrieving passwords and other secrets
EOF

sudo chown -R root:root "${DEST_DIR}"
dpkg-deb --build "${DEST_DIR}"

popd
