{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
    {% for var, value in item.env.items() %}
        {% if value %}
            ENV {{ var }} {{ value }}
        {% endif %}
    {% endfor %}
{% endif %}

RUN apt -y update
# Mostly for add-apt-repository and systemctl to work
RUN apt -y install --no-install-recommends sudo bash gnupg software-properties-common systemd cron
