---

# https://framagit.org/rg/ansible-role-template/-/blob/79e3f176/molecule/default/molecule.yml#L13
# https://ericsysmin.com/2020/05/10/using-a-dockerfile-repo-for-molecule-dockerfiles/
# https://gitlab.com/aussielunix/ansible/molecule-containers
#
# systemd is necessary for most of the roles, enablement requires >= WSL 0.67.6
# Stable: install manually from https://github.com/microsoft/WSL/releases
# Insider: update with wsl --update
#
# There's no init/systemd in the base Ubuntu Docker image, and prepare.yml runs
# AFTER 'molecule create', which therefore fails with 'command not found'.
# Therefore, we need to ensure systemd is present with a custom Dockerfile.
#
# We could specify separate Dockerfiles with dockerfile: 'foo.j2', but it's
# probably less redundant to have one unified Dockerfile with jinja filters for
# different distros. Dockerfile.j2 is the default filename, so if you supply
# that, Molecule will use that automatically.
#
# Apparently the SYS_ADMIN capability is not sufficient if we don't do bind
# mounts; we need privileged instead.
#
# We need to explicitly disable 'override_command', otherwise Molecule will pick
# CMD on its own. This appears to work on Rocky, but not on Ubuntu. So stop the
# guess work and specify things explicitly.

driver:
  name: docker
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
lint: |
  set -e
  yamllint --strict --config-file ../.yamllint .
  ansible-lint --strict --config-file ../.ansible-lint

platforms:

  - name: rocky9
    groups:
      - rhel
    image: rockylinux:9
    privileged: true
    override_command: false

  - name: ubuntu2204
    groups:
      - ubuntu
    image: ubuntu:22.04
    privileged: true
    override_command: false
