#!/bin/bash

# sudo apt -y install git meson jose libjose-dev cmake libjansson-dev libluksmeta-dev tang curl tpm2-tools luksmeta libpwquality-tools pkg-config libglib2.0-dev libudisks2-dev libaudit-dev

set -eu

PKG_NAME='clevis'

PKG_VER="14+git$(date +%Y%m%d)"
GIT_REV=1285061
PKG_BUILD=4

#PKG_VER="14"
#PKG_BUILD=2

SRC_DIR="${PWD}"
TMP_DIR="/tmp/noobuntu"
WORK_DIR="${TMP_DIR}/${PKG_NAME}"
DEST_DIR="${TMP_DIR}/${PKG_NAME}_${PKG_VER}-${PKG_BUILD}"

sudo rm -rf ${TMP_DIR}

mkdir -p ${WORK_DIR}
mkdir -p ${DEST_DIR}
cp clevis.patch ${WORK_DIR}

pushd ${WORK_DIR}

git clone https://github.com/latchset/clevis.git
cd clevis
git checkout ${GIT_REV}

#wget https://github.com/latchset/clevis/releases/download/v${PKG_VER}/clevis-${PKG_VER}.tar.xz
#tar xf clevis-${PKG_VER}.tar.xz
#cd clevis-${PKG_VER}

# TODO remove once fixed upstream
# https://github.com/latchset/clevis/issues/158
# https://github.com/latchset/clevis/issues/145
patch -i ../clevis.patch -p1

meson build --prefix=/usr
# --libdir=/usr/lib
ninja -C build
sudo ninja -C build test
DESTDIR=${DEST_DIR} ninja -C build install

mkdir -p "${DEST_DIR}/DEBIAN"

cat << EOF > "${DEST_DIR}/DEBIAN/control"
Package: ${PKG_NAME}
Version: ${PKG_VER}-${PKG_BUILD}
Section: base
Priority: optional
Architecture: amd64
Depends: libc6 (>= 2.27), tpm2-tools (>= 4.1.1), jose (>= 10-2build1), libjansson4 (>= 2.11), luksmeta (>= 8-3build1), libpwquality-tools (>= 1.4.0), auditd (>= 1:2.8.2), udisks2 (>= 2.7.6), libglib2.0-0 (>= 2.56.4), tang (>= 6), curl (>= 7.58.0)
Maintainer: Viktor Berke <github.bviktor@outlook.com>
Description: Automated Encryption Framework
EOF

cat << EOF > "${DEST_DIR}/DEBIAN/postinst"
/usr/sbin/update-initramfs -c -k all
EOF
chmod +x "${DEST_DIR}/DEBIAN/postinst"

cat << EOF > "${DEST_DIR}/DEBIAN/postrm"
/usr/sbin/update-initramfs -c -k all
EOF
chmod +x "${DEST_DIR}/DEBIAN/postrm"

sudo chown -R root:root "${DEST_DIR}"
dpkg-deb --build "${DEST_DIR}"

popd
