#!/bin/bash

# sudo apt -y install git libsecret-1-dev libglib2.0-dev

set -eu

PKG_NAME='git-credential-libsecret'

GIT_VER=$(git --version | cut -d' ' -f3)
PKG_VER=${GIT_VER}
PKG_BUILD=2

SRC_DIR="${PWD}"
TMP_DIR="/tmp/noobuntu"
WORK_DIR='/usr/share/doc/git/contrib/credential/libsecret'
DEST_DIR="${TMP_DIR}/${PKG_NAME}_${PKG_VER}-${PKG_BUILD}"

sudo rm -rf ${TMP_DIR}
mkdir -p "${DEST_DIR}/${WORK_DIR}"

pushd ${WORK_DIR}

sudo make clean
sudo make
cp git-credential-libsecret "${DEST_DIR}/${WORK_DIR}/"
sudo make clean

mkdir -p "${DEST_DIR}/DEBIAN"

cat << EOF > "${DEST_DIR}/DEBIAN/control"
Package: ${PKG_NAME}
Version: ${PKG_VER}-${PKG_BUILD}
Section: base
Priority: optional
Architecture: amd64
Depends: libglib2.0-0 (>= 2.56.4), libsecret-1-0 (>= 0.18.6), git (>= ${GIT_VER}), seahorse (>= 3.20.0)
Maintainer: Viktor Berke <github.bviktor@outlook.com>
Description: Git credential helper using libsecret
EOF

sudo chown -R root:root "${DEST_DIR}"
dpkg-deb --build "${DEST_DIR}"

popd
