#!/bin/bash

set -eu

docker --version &> /dev/null || true

if [ ! $? -ne 0 ]
then
    echo -e "\e[31mError! Docker not found. Ensure Docker is installed and running.\e[0m"
    exit 1
fi

if [ ! -f 'tests/main.yml' ]
then
    echo -e "\e[31mError! Tests not found. Ensure you're in the right directory.\e[0m"
    exit 1
fi

arguments=()
platform="fedora:37"

while [[ $# -gt 0 ]]
do
    case "${1}" in
      --platform)
        platform="${2}"
        shift 2
        ;;
      *)
        arguments+=("${1}")
        shift 1
        ;;
    esac
done

role=$(basename ${PWD} | sed 's/ansible-galaxy-//')

echo -e "\nRunning Galaxy role tests on:\n - Role: \e[36m${role}\e[0m\n - Platform: \e[36m${platform}\e[0m\n"

# Fire up instance
CONT_ID=$(docker run --rm -v $(pwd):/repo -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /tmp --tmpfs /run --privileged --detach "bviktor/ansible-systemd-${platform}")
# Install dependencies
docker exec "${CONT_ID}" bash -c "if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml -p ..; fi"
# Run the actual tests
docker exec "${CONT_ID}" bash -c "ANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook ${arguments[*]} tests/main.yml"
# Let us check stuff before exiting
docker exec -it "${CONT_ID}" bash
# Stop instance
docker stop "${CONT_ID}"
