---
- name: "Adjust defaults for {{ item.section }}/{{ item.option }}"
  ini_file:
    path: /usr/local/share/glib-2.0/schemas/20_corporate-settings.gschema.override
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
    create: true
    mode: '0644'
  notify: Compile GLib schema

# glib-compile-schemas accepts only one dir and skips overrides without schema definitions
# so we need to put them in the same dir, but use symlinks to keep our local changes separated
- name: Symlink schema override from local to system dir
  file:
    src: /usr/local/share/glib-2.0/schemas/20_corporate-settings.gschema.override
    dest: /usr/share/glib-2.0/schemas/20_corporate-settings.gschema.override
    state: link
  notify: Compile GLib schema
