---
- name: Reload AppArmor profiles
  systemd:
    name: apparmor
    state: reloaded

- name: Update PAM auth
  command:
    cmd: "{{ item }}"
  loop:
    - pam-auth-update --enable fscrypt
    - pam-auth-update --enable keyinit-fix

- name: Update GRUB
  command:
    cmd: update-grub

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: Restart Defender ATP
  systemd:
    name: mdatp
    state: restarted
