---
- hosts: "{{ target | default('127.0.0.1') }}"
  connection: "{% if target is defined %}ssh{% else %}local{% endif %}"
  become: true
  module_defaults:
    apt:
      force_apt_get: true
  roles:
# avoid installing / removing NV back and forth
#  - update
    - nvidia
