---
# Bootstrap the package manager, required in Ubuntu Docker
- name: Update package manager cache
  apt:
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

# The module docs don't mention it, but this is required for apt_repository to work
- name: Install apt basics
  apt:
    name: gnupg
    state: latest
  when: ansible_pkg_mgr == 'apt'

# TODO enable once available for ARM64
- name: Add Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    mode: '0644'
  when: (ansible_pkg_mgr == 'apt') and (ansible_architecture != 'aarch64')

- name: Enable EPEL repo
  dnf:
    name: epel-release
    state: latest
  when: ansible_pkg_mgr == 'dnf'

- name: Install Ansible
  apt:
    name: ansible
    state: latest
  when: ansible_pkg_mgr == 'apt'

- name: Install Ansible
  dnf:
    name: ansible
    state: latest
  when: ansible_pkg_mgr == 'dnf'

- name: Show IP on login screen
  replace:
    path: /etc/issue
    regexp: '(Ubuntu .*)\\l$'
    replace: '\1\\l (\\4)'
  when: ansible_pkg_mgr == 'apt'
