# TODO enable once available for ARM64
- name: Add Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    mode: '0644'
  when: (ansible_distribution == 'Ubuntu') and (ansible_architecture != 'aarch64')

- name: Enable EPEL repo
  yum:
    name: epel-release
  when: ansible_distribution == 'CentOS'

- include_role:
    name: rhelrepo
  loop:
  - rhel-7-server-ansible-2-rpms
  when: ansible_distribution == 'RedHat'

- name: Install Ansible
  apt:
    name: ansible
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: Install Ansible
  yum:
    name: ansible
    state: latest
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')

- name: Show IP on login screen
  replace:
    path: /etc/issue
    regexp: '(Ubuntu .*)\\l$'
    replace: '\1\\l (\\4)'
  when: ansible_distribution == 'Ubuntu'
