---
- name: Check if appstream config exists
  stat:
    path: /etc/apt/apt.conf.d/50appstream
  register: appstream_result

- name: Fix multi-arch apt behavior
  replace:
    path: /etc/apt/apt.conf.d/50appstream
    regexp: 'NATIVE_ARCHITECTURE'
    replace: 'ARCHITECTURE'
  when: appstream_result.stat.exists

- name: Ignore missing HiDPI icons in apt-mirror
  replace:
    path: /etc/apt/apt.conf.d/50appstream
    after: 'deb::DEP-11-icons-hidpi\s*{'
    before: '};'
    regexp: '.*'
  when: appstream_result.stat.exists

#- name: "Proper multi-arch sources.list for {{ ansible_distribution_release }}"
#  template:
#    src: sources.list.j2
#    dest: /etc/apt/sources.list
