---
- name: Deploy APT maintenance job
  copy:
    src: apt-maintenance
    dest: /etc/cron.daily/apt-maintenance
    mode: '0755'
  notify: Restart cron service
  when: no_apt_maintenance is not defined

- name: Remove APT maintenance job
  file:
    path: /etc/cron.daily/apt-maintenance
    state: absent
  notify: Restart cron service
  when: no_apt_maintenance is defined

- name: Update apt cache
  apt:
    update_cache: true
  changed_when: false

- name: Update all packages
  apt:
    upgrade: dist
    update_cache: false

- name: Remove obsolete packages
  apt:
    autoremove: true

- name: List packages needing a reboot
  copy:
    src: 99-reboot-pkgs
    dest: /etc/update-motd.d/99-reboot-pkgs
    mode: '0755'

- name: Check if release upgrader is installed
  shell:
    cmd: apt list --installed | grep ubuntu-release-upgrader-core
  failed_when: false
  changed_when: false
  register: ubuntu_release_upgrader

- name: Disable release upgrade prompts
  ini_file:
    path: /etc/update-manager/release-upgrades
    section: DEFAULT
    option: Prompt
    value: never
    no_extra_spaces: true
    mode: '0644'
  when: ubuntu_release_upgrader.rc == 0
