---
# Leave this here for historical purposes
- name: Update yum info and all OS packages
  yum:
    name: '*'
    state: latest

- name: Install yum-cron
  yum:
    name: yum-cron

- name: Enable yum-cron service
  systemd:
    name: yum-cron.service
    state: started
    enabled: true

- name: Enable applying updates
  ini_file:
    path: /etc/yum/yum-cron.conf
    section: commands
    option: apply_updates
    value: 'yes'
    mode: '0644'
  notify: Restart yum-cron service
