- name: Update yum info and all OS packages
  yum:
    name: '*'
    state: latest

- name: Install dnf-automatic
  yum:
    name: dnf-automatic

- name: Enable applying updates
  ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: apply_updates
    value: 'yes'
    mode: '0644'

- name: Enable dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes
