---
# SSSD services are socket-activated on 20.04 and SSSD throws a misconfiguration error if set
# We could remove manually from sssd.conf, but that's generated *after* joined to AD via realmd, so it'd take 2 playbook runs to be fixed
# Use this idempotent workaround instead, where the empty conf.d value overrides the sssd.conf value
- include_role:
    name: sssd
  loop:
    - { file: 'services', section: 'sssd', option: 'services', value: "{% if ansible_distribution_version == '18.04' %}nss, pam, sudo{% else %}{% endif %}" }
  when: ansible_distribution == 'Ubuntu'

# https://bugs.launchpad.net/ubuntu/+source/sssd/+bug/1723350/comments/49
# https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path
- include_role:
    name: sedtemplate
  loop:
    - { desc: 'SSSD systemd unit', regex: '/^Wants=.*/a After=systemd-resolved.service', src: '/lib/systemd/system/sssd.service', dest: '/etc/systemd/system/sssd.service'}
  when: ansible_distribution == 'Ubuntu'

- name: Set up SSSD options
  ini_file:
    path: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: sssd, option: services, value: 'nss, pam, sudo' }
    - { section: sssd, option: config_file_version, value: 2 }
    - { section: sssd, option: domains, value: "{{ ad_domain }}" }
    - { section: "domain/{{ ad_domain }}", option: id_provider, value: ad }
    - { section: "domain/{{ ad_domain }}", option: access_provider, value: ad }
    - { section: "domain/{{ ad_domain }}", option: cache_credentials, value: 'True' }
    - { section: "domain/{{ ad_domain }}", option: override_homedir, value: /home/%d/%u }
    - { section: "domain/{{ ad_domain }}", option: default_shell, value: /bin/bash }
  # TODO on EL krb5.keytab doesn't exist until domain joined
  # and SSSD fails to start without it on EL7
  #notify: Restart SSSD service
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')
