---
# this should work regardless of unit path or service state
- name: Check if SSSD service is present # noqa command-instead-of-module
  command:
    cmd: systemctl cat sssd.service
  failed_when: false
  changed_when: false
  register: sssd_service

- include_tasks: confd.yml
  when: sssd_service.rc == 0
