# make sure these are the last
- name: Remove broken system monitor snap
  snap:
    name: gnome-system-monitor
    state: absent

- name: Remove Hiri snap
  snap:
    name: hiri
    state: absent

# https://bugs.launchpad.net/ubuntu/+source/totem/+bug/1780475
- name: Remove packages breaking video playback
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - mesa-va-drivers
    - gstreamer1.0-vaapi

# static service, mask is necessary
- name: Disable automatic UEFI updates
  systemd:
    name: fwupd
    enabled: no
    masked: yes
    state: stopped
    
- name: Purge Microsoft Edge beta and dev packages
  apt:
    name: "{{ packages }}"
    purge: yes
  vars:
    packages:
    - microsoft-edge-beta
    - microsoft-edge-dev

- name: Delete Microsoft Edge beta and dev repos
  file:
    name: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  loop:
  - microsoft-edge-beta.list
  - microsoft-edge-dev.list
