---
- name: Create Defender ATP config folder
  file:
    path: /etc/opt/microsoft/mdatp
    state: directory
    recurse: true

- name: Deploy Defender ATP onboarding config
  copy:
    src: mdatp_onboard.json
    dest: /etc/opt/microsoft/mdatp/mdatp_onboard.json
    mode: '0644'
  notify: Restart Defender ATP

- include_role:
    name: 3rdparty
  loop:
    - { name: 'Defender ATP', gpg_url: 'https://packages.microsoft.com/keys/microsoft.asc', repo_file: 'microsoft-prod', package: 'mdatp' }

# TODO restart MDATP hourly for now, otherwise it kills the system within a day or so
- include_role:
    name: sedtemplate
  loop:
    - { desc: 'MDATP systemd unit', regex: '/^Restart=.*/a TimeoutStopSec=10', src: '/lib/systemd/system/mdatp.service', dest: '/etc/systemd/system/mdatp.service'}

- name: Enable and start Defender ATP service
  systemd:
    name: mdatp
    state: started
    enabled: true
