- include_role:
    name: gsettings
  loop:
    # default domain for browsing shares
    # TODO use {{ ad_domain.split(".")[0] }} conditionally if set
    - { section: "org.gnome.system.smb", option: "workgroup", value: "'AD'" }
    # https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/561370
    - { section: "org.gnome.Terminal.Legacy.Profile", option: "use-theme-transparency", value: 'false' }
    # terminal accelerator key conflicting with MC
    - { section: "org.gnome.Terminal.Legacy.Settings", option: "menu-accelerator-enabled", value: 'false' }
    # screenshot keyboard shortcut identical to Windows
    - { section: "org.gnome.settings-daemon.plugins.media-keys{% if ansible_distribution_version == '20.04' %}.deprecated{% endif %}", option: "area-screenshot-clip", value: "'<Shift><Super>s'" }
    # disable switch apps shortcut
    - { section: "org.gnome.desktop.wm.keybindings", option: "switch-applications", value: "[]" }
    # enable switch windows shortcut
    - { section: "org.gnome.desktop.wm.keybindings", option: "switch-windows", value: "['<Super>Tab','<Alt>Tab']" }
    # bump lock screen timeout to 10 minutes
    - { section: "org.gnome.desktop.session", option: "idle-delay", value: "600" }
    # use location entry instead of pathbar
    #- { section: "org.gnome.nautilus.preferences", option: "always-use-location-entry", value: 'true' }
    # disable notifications on the lock screen
    - { section: "org.gnome.desktop.notifications", option: "show-in-lock-screen", value: 'false' }

# TODO 20.04 compat
- name: Make grouped window preview order static
  patch:
    src: static-dock-preview-order.patch
    dest: /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/windowPreview.js
    backup: yes
  when: ansible_distribution_version == '18.04'
