---
# IPv6 breaks PPAs and 3rd-party repos, amongst others things
- include_role:
    name: bviktor.sysctl
  loop:
    - { file: '99-disable-ipv6', option: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { file: '99-disable-ipv6', option: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
    - { file: '99-disable-ipv6', option: 'net.ipv6.conf.lo.disable_ipv6', value: '1' }
