---
- include_role:
    name: bviktor.thirdparty
  loop:
    - { name: 'Insync', gpg_server: 'keyserver.ubuntu.com', gpg_id: 'ACCAF35C', repo_file: 'insync', package: '{{ packages }}', repo_overwrite: true }
  vars:
    packages:
      - insync
      - insync-nautilus

- name: Enable Qt display scaling
  lineinfile:
    path: /etc/environment
    regexp: '^QT_AUTO_SCREEN_SCALE_FACTOR=.*'
    line: QT_AUTO_SCREEN_SCALE_FACTOR=1

#- name: Fix HiDPI display
#  replace:
#    path: /usr/share/applications/insync.desktop
#    regexp: '^Exec=insync(.*)'
#    replace: 'Exec=env QT_AUTO_SCREEN_SCALE_FACTOR=1 insync\1'
