---
- name: Check if pgAdmin is installed
  shell:
    cmd: apt list --installed 2>/dev/null | grep pgadmin4
  changed_when: false
  failed_when: false
  register: apt_pgadmin

- name: Check if pgAdmin desktop is installed
  shell:
    cmd: apt list --installed 2>/dev/null | grep pgadmin4-desktop
  changed_when: false
  failed_when: false
  register: apt_pgadmin_desktop

- name: Remove legacy pgAdmin
  command:
    cmd: apt purge -y --autoremove pgadmin4*
  when: apt_pgadmin.rc == 0 and apt_pgadmin_desktop.rc != 0

- include_role:
    name: 3rdparty
  loop:
    - { name: 'pgAdmin', gpg_url: 'https://www.pgadmin.org/static/packages_pgadmin_org.pub', repo_file: 'pgadmin4', package: "{{ packages }}" }
  vars:
    packages:
      - pgadmin4
      - pgadmin4-desktop
