---
- name: Remove MS Teams snap version
  snap:
    name: teams-for-linux
    state: absent

- name: Remove MS Teams appimage version
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /Applications/msteams
    - /usr/share/applications/msteams.desktop
    - /usr/share/pixmaps/com.microsoft.teams.png

- name: Remove unofficial Teams deb
  apt:
    name: teams-for-linux
    state: absent

- name: Remove insider Teams deb
  apt:
    name: teams-insiders
    state: absent

- include_role:
    name: 3rdparty
  loop:
    - { name: 'Teams', gpg_url: 'https://packages.microsoft.com/keys/microsoft.asc', repo_file: 'teams', package: 'teams' }
