---
- name: Install HWE X.Org
  apt:
    name: "xserver-xorg-hwe-{{ ansible_distribution_version }}"
    state: latest
  # TODO enable for 20.04 once available
  when: ansible_distribution_version == '18.04'

#- name: Check if any NV version is installed
#  shell:
#    dpkg -l | grep -E "nvidia-driver-[0-9]{3}"
#  failed_when: no
#  changed_when: no
#  register: nv_any

- name: Check if current NV version is installed
  shell:
    cmd: apt list --installed | grep -E "nvidia-driver-{{ nvidia_version | default(nvidia_default_version) }}"
  failed_when: false
  changed_when: false
  register: nv_current
#  when: nv_any.rc == 0

- name: Check if mismatching NV packages are installed
  shell:
    cmd: apt list --installed | grep -E 'nvidia.*\-.*[0-9]{3}\/' | grep -v '{{ nvidia_version | default(nvidia_default_version) }}'
  failed_when: false
  changed_when: false
  register: nv_mismatch

- include_role:
    name: nvpurge
  #when: nv_any.rc == 0 and nv_current.rc != 0
  when: nv_current.rc != 0 or nv_mismatch.rc == 0

- include_role:
    name: desktopcheck

- name: "Install NV driver v{{ nvidia_version | default(nvidia_default_version) }}"
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: true
    install_recommends: "{% if target_is_desktop %}yes{% else %}no{% endif %}"
  vars:
    packages:
      - "nvidia-driver-{{ nvidia_version | default(nvidia_default_version) }}"
      - "nvidia-dkms-{{ nvidia_version | default(nvidia_default_version) }}"
      - "nvidia-kernel-source-{{ nvidia_version | default(nvidia_default_version) }}"
      - "nvidia-kernel-common-{{ nvidia_version | default(nvidia_default_version) }}"

- name: Install NVIDIA X Server Settings
  apt:
    name: nvidia-settings
    state: latest
  when: target_is_desktop
