---
- name: Install mokutil
  apt:
    name: mokutil
    state: present

- name: Check Secure Boot state
  command: mokutil --sb-state
  failed_when: false
  changed_when: false
  register: sb_state

- fail:
    msg: Secure Boot appears to be enabled. Check Secure Boot settigns in the UEFI!
  when: ("SecureBoot disabled" not in sb_state.stdout) and ("This system doesn't support Secure Boot" not in sb_state.stderr)
