---
# this should work regardless of unit path or service state
- name: Check if UFW service is present
  shell: systemctl cat ufw.service
  failed_when: false
  changed_when: false
  register: ufw_service

- name: Disable UFW
  systemd:
    name: ufw
    enabled: false
    state: stopped
  when: ufw_service.rc == 0

# take a leap of faith, SSH is enabled by default
# and the firewalld module does not work on Ubuntu
# even though the module is found in python3 shell
- name: Install firewalld
  apt:
    name: firewalld
    state: latest
  register: installed_firewalld
  when: ansible_distribution == 'Ubuntu'

- name: Install firewalld
  yum:
    name: firewalld
    state: latest
  register: installed_firewalld
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')

# necessary for Ansible to work remotely
#- name: Enable SSH access
#  firewalld:
#    service: ssh
#    state: enabled
#    permanent: yes
#    immediate: yes
#    offline: yes

- name: Enable firewalld
  systemd:
    name: firewalld
    enabled: true
    state: started
  when: k8s_node is not defined

- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: false
    state: stopped
  when: k8s_node is defined

# make sure
#- name: "Enable SSH service"
#  shell: "firewall-cmd --permanent --add-service=ssh && firewall-cmd --reload"
#  register: fw_ssh
#  changed_when: ("ALREADY_ENABLED" not in fw_ssh.stderr)
